### PR TITLE
Follow original author's updates

### PR DESCRIPTION
**Pull request by jiazheng0609**
Target: https://github.com/PanierAvide/panieravide.github.io/commit/1f9017a55bc7d991238d056e6ec4d3739c3d7c23

### CODE REVIEW

**Comment by jiazheng0609** [comment]
Sorry, I used the pull request function incorrectly.
I was trying to merge your latest commit into my forked repository.

**Comment by PanierAvide** [comment]
No problem, that's cool you translated in Chinese ;) Maybe we can work on a common translation system, making your translation available to everyone ?

**Comment by jiazheng0609** [comment]
I'm willing to do that!

**Comment by PanierAvide** [comment]
Nice, I opened issue #23 to do so :)

**Pull request closed without merging**
